### ISSUE TITLE
Issues with note and master control updation

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#188] opened 2021-02-24 17:53 UTC
I haven't used notes for more than a week. So I don't when it got wrong. I couldn't open note editor when I checked 2 days before. Nothing opens when I click new note. If I click on note editor.uba it shows info on study window. If I click on edit button on previous notes in study window, nothing happens.

Don't know whether it's an issue. But after adding a Bible or commentaries doesn't update on master control. Just noticed after the downloading issue got fixed. After a restart it is updated.

**Comment by eliranwong** [comment] 2021-02-24 18:54
> I haven't used notes for more than a week. So I don't when it got wrong. I couldn't open note editor when I checked 2 days before. Nothing opens when I click new note. If I click on note editor.uba it shows info on study window. If I click on edit button on previous notes in study window, nothing happens.
> 
> Don't know whether it's an issue. But after adding a Bible or commentaries doesn't update on master control. Just noticed after the downloading issue got fixed. After a restart it is updated.

You mentioned two different things.  I suggest next time you may consider writing a single issue for a single issue.

regarding notes, can you try again, I cannot replicate the issue.  I am on Focus menu layout.  I experienced once that "edit" button does nothing after menu loaded to Aleph, but the issue didn't persist after loading back to Focus layout and restarting the app.  That happened once to me, but I cannot replicate again.

regarding modules shown in control panel, you are right that restarting the app reloads the resource lists displayed on control panel.

**Comment by eliranwong** [comment] 2021-02-24 18:57
I may consider reloading the Master control panel after a module is installed.  I have not decided yet, restarting the app is needed anyway for installing third-party modules, because I do not know when users place a new file in the marvelData folder.

an alternative is that I may consider adding a function to manually reload the resource list of control panel if that helps.

I will think about it.  Thanks for your report.

**Comment by eliranwong** [comment] 2021-02-24 20:00
in version 21.64

* Add "Reload Resources" under "Master Control" section on "Focus menu layout".
    - This is useful for reloading resources displayed on Master Control panel without restarting the app.

**Comment by onegladiator4u** [comment] 2021-02-24 20:04
>  I suggest next time you may consider writing a single issue for a single issue.

Sure brother.

I was using focus menu. I tried classic menu after restart too. Note editor not opening.

My debug info
![image](https://user-images.githubusercontent.com/48617390/109058735-5cc8b300-7709-11eb-8daf-11e24016d226.png)

**Comment by onegladiator4u** [comment] 2021-02-24 20:07
> 
> 
> in version 21.64
> 
>     * Add "Reload Resources" under "Master Control" section on "Focus menu layout".
>       
>       * This is useful for reloading resources displayed on Master Control panel without restarting the app.

Ok got it bro

**Comment by eliranwong** [comment] 2021-02-24 20:23
> > I suggest next time you may consider writing a single issue for a single issue.
> 
> Sure brother.
> 
> I was using focus menu. I tried classic menu after restart too. Note editor not opening.
> 
> My debug info
> ![image](https://user-images.githubusercontent.com/48617390/109058735-5cc8b300-7709-11eb-8daf-11e24016d226.png)



> > I suggest next time you may consider writing a single issue for a single issue.
> 
> Sure brother.
> 
> I was using focus menu. I tried classic menu after restart too. Note editor not opening.
> 
> My debug info
> ![image](https://user-images.githubusercontent.com/48617390/109058735-5cc8b300-7709-11eb-8daf-11e24016d226.png)

I woupd like to know two things:

1) was there any error message on your powershell when you try to launch note editor.  can you try to launch UBA with powershell and check?

2) can you open note editor by clicking "Edit Note" on Master Control panel

**Comment by eliranwong** [comment] 2021-02-24 21:04
I can confirm that there is a bug causing Note Editor not able to be opened.  I will fix it.

**Comment by eliranwong** [comment] 2021-02-24 21:10
Note Editor fixed in version 21.65: https://github.com/eliranwong/UniqueBible/commit/b7ca2940b0d23ae50dc0715a4336d45abc1bfed7

**Comment by onegladiator4u** [comment] 2021-02-25 07:17
Note editor is working and extra python window is no more too.
Thank you.

**Closed** 2021-02-25 07:18 UTC
Labels: bug
