### ISSUE TITLE
BDB in Windows Version not Loading 

### ISSUE THREAD

**Issue by hebrewmatthew** [eliranwong/UniqueBible#234] opened 2021-03-04 13:21 UTC
This has been an issue on the Windows version for almost a year. I've installed on two different devices. Never can use BDB, but all the other lexicons work when accessed from dropdown menu. After clicking "analytical lexicon button" dropdown fails to load any BDB entries. 
![unique_bible_bdb_issue](https://user-images.githubusercontent.com/46854918/109969901-100d4b00-7cba-11eb-8e35-da5dabf4a69c.PNG)

**Comment by eliranwong** [comment] 2021-03-04 15:38
@hebrewmatthew 

I would like to ask if the issue is only on Windows or not?

can you use BDB on another device.

From your screenshot, I understand why you can open an entry from BDB.  E70020 is code for lookup Hebrew word based on ETCBC word.  It is not a standard Strong number.  To look for the same work in BDB in your exmple

(I note that WORD:::1:::33 is in your screenshot.  I use this as an example)

You should select the Strong's number H559 instead of E70020.

![Screenshot_20210304_153322](https://user-images.githubusercontent.com/25262722/109988383-618bf900-7cff-11eb-8cd7-0eb846ddc7d4.png)

![Screenshot_20210304_153159](https://user-images.githubusercontent.com/25262722/109988414-681a7080-7cff-11eb-8562-85049b93a9c9.png)

There is another possibility:

In case selecting H559 still does not work for you, it is possible that your BDB.lexicon file is not a valid file,

please check if you have BDB.lexicon in folder "marvelData/lexicons"

when you locate the file BDB.lexicon, check its check.  it should be around 80MB.

if you found it about 0KB size, that means your file is not a valid file.  please delete it and redownload BDB.lexicon and it should work as expected.

**Comment by eliranwong** [comment] 2021-03-08 15:52
@hebrewmatthew can you kindly let us know if the issue is solved yet?  thank you.

**Comment by eliranwong** [comment] 2021-03-18 09:52
@hebrewmatthew We close this issue now, as this is not a bug and we gave instructions above lookup in BDB lexicon.  Feel free to reopen the issue if you have further question.  Thanks.

**Closed by eliranwong** 2021-03-18 09:52 UTC
