### ISSUE TITLE
i can use "Brown-driver-Briggs Hebrew-english Lexicon"

### ISSUE THREAD

**Issue by fillgun** [eliranwong/UniqueBible#1] opened 2019-11-22 06:02 UTC
hi~ first all thank you for your great bible program ^^

i can use "Brown-driver-Briggs Hebrew-english Lexicon" and
i can see cmd "sqlite3.PoearationalError: no such table : BDB"

how can i do ??

thank you 
God bless you

**Comment by eliranwong** [comment] 2019-11-27 12:25
Hi, can you give me some more details.  Did you try reinstalling the BDB lexicon?

**Comment by fillgun** [comment] 2019-11-27 19:50
how to reinstall the BDB lexicon?

I read it in the MTB or nasb Bible.  Click on a word or strong number to go to lexicon and select a BDB dictionary.
There is no response or not found.

For example, if i select בְּרֵאשִׁ֖ית in Genesis 1: 1, i cannot see anything.
However, on the website (marvel.bible) I confirmed that it worked.

Not all words are.
i can see בֹּ֫הוּ in verse Genesis 1: 2.

**Comment by eliranwong** [comment] 2019-11-27 22:11
From the error, "no such table : BDB", it looks like you may be using an old version.  May I ask if you are using the latest version 5.5?  You can check by opening main.py or config.py with a text editor like notepad.

Or, you can manually update the app, by using all latest files from this repository and try again.  Please freely let me know if it is still not working.  Thanks.

I am using the latest code, BDB works fine as expected.  I cannot reproduce the error.

**Comment by fillgun** [comment] 2019-11-28 01:54
I using version 5.5 .. and I try to reinstall. but same problem ㅠ.ㅠ


I use python 3.7.2 on Mac air 2012 mid.. os High Sierra

**Comment by eliranwong** [comment] 2019-11-28 07:49
I will try on a mac similar to your one and get back to you.  thanks.

**Comment by eliranwong** [comment] 2019-12-03 14:29
I had tested on my Mac mini, it seems there is an issue.  I will check further and fix if possible.  Thanks for reporting the issue.  Blessings.

**Comment by fillgun** [comment] 2019-12-08 18:31
thank you~~ ^^ God bless you

**Comment by eliranwong** [comment] 2019-12-11 23:17
I file the errors below first, I am checking ...:

The feature works fine in all my devices, except my old mac mini (Late 2012).

LEXICON:::BDB:::H7225
Traceback (most recent call last):
  File "/Users/eliranwong/UniqueBible-master/gui.py", line 2114, in studyTextCommandChanged
    self.textCommandChanged(newTextCommand, "study")
  File "/Users/eliranwong/UniqueBible-master/gui.py", line 2128, in textCommandChanged
    self.runTextCommand(newTextCommand, True, source)
  File "/Users/eliranwong/UniqueBible-master/gui.py", line 2136, in runTextCommand
    view, content = self.textCommandParser.parser(textCommand, source)
  File "/Users/eliranwong/UniqueBible-master/TextCommandParser.py", line 98, in parser
    return interpreters[keyword](command, source)
  File "/Users/eliranwong/UniqueBible-master/TextCommandParser.py", line 925, in textLexicon
    content = "<hr>".join([lexicon.getContent(entry) for entry in entries.split("_")])
  File "/Users/eliranwong/UniqueBible-master/TextCommandParser.py", line 925, in <listcomp>
    content = "<hr>".join([lexicon.getContent(entry) for entry in entries.split("_")])
  File "/Users/eliranwong/UniqueBible-master/ToolsSqlite.py", line 563, in getContent
    imageSqlite.exportImage(imgModule, imgEntry)
  File "/Users/eliranwong/UniqueBible-master/ToolsSqlite.py", line 89, in exportImage
    self.cursor.execute(query, (entry,))
sqlite3.OperationalError: no such table: BDB

**Comment by eliranwong** [comment] 2019-12-12 00:34
@fillgun 

I found where the issue is.  There is a missing file in your UniqueBible folder.

I will fix my codes in future release.

To have a temporary fix on your side.

1) close the app first
2) go to UniqueBible folder > marvelData
3) delete the file "images.sqlite"
4) open the app again
5) Type the following in the command field of UniqueBible.app's main window:

> _image:::

6) Following instruction of "Download Helper" to download the missing file.
7) run BDB lexicon again and check

many thanks for reporting the issue.

**Comment by eliranwong** [comment] 2019-12-12 00:39
The issue happens not only in mac, I will fix the codes in future release.

**Comment by fillgun** [comment] 2019-12-12 05:15
It's work!!! thank you for fixing!

I am a seminary student. I introduced this program to my friends. 
Then my friends liked it very much. So I thought it would be nice to make a Korean version.
Can I make a Korean version?

**Comment by eliranwong** [comment] 2019-12-12 08:13
@fillgun 

you can:

- import a Korean bible

- use Korean abbreviations on bible books

- translate the interface to Korean

- join my slack group, so we can talk through the process there

below is an invitation link:

https://join.slack.com/t/marvelbible/shared_invite/enQtNDYyMTAxNTMwNTY2LWU4YzUyMzUxYWQxNDNiNDhjMmYwMjdjZTQ0ZWQyODg3NTA1MWZmZmM1ZThmOWFlMGUzZWUxNTllNmMxNTgzYTU

**Comment by eliranwong** [comment] 2019-12-12 18:54
this issue was fixed in version 5.6

**Closed** 2019-12-13 15:54 UTC
