### ISSUE TITLE
Question on context plugin "save as mp3"

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#917] opened 2022-02-24 02:13 UTC
When I highlight text, right-click and select "save as mp3" as English, it pulls up the Save as screen. I enter a name (I have tried text4 and text4.mp3) and save the file. When I then search for that file it does not appear to exist. Am I missing something?

**Comment by eliranwong** [comment] 2022-02-24 09:37
any error message on terminal?

**Comment by darrelwright** [comment] 2022-02-24 10:49
Yes there is:

Error in sys.excepthook:
Traceback (most recent call last):
   File "/home/darrel/UniqueBible/main.py", line 470, in global_excepthook
     print(traceback.format_exc())
AttributeError: 'traceback' object has no attribute 'format_exc'

Original exception was:
Traceback (most recent call last):
   File "/home/darrel/UniqueBible/gui/WebEngineView.py", line 899, in 
googleTextToSpeechAudio
     from gtts import gTTS
   File 
"/home/darrel/UniqueBible/venv/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", 
line 142, in _import
     return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'gtts'

**Comment by eliranwong** [comment] 2022-02-24 16:28
From the message "ModuleNotFoundError: No module named 'gtts'", it appears that your computer does not have gTTS installed.

**Comment by darrelwright** [comment] 2022-02-24 19:54
Not true. I can play the GTTS audio perfectly.

**Comment by darrelwright** [comment] 2022-02-24 21:32
It is true. gtts is missing, gtts-cli is installed. But when I run "pip3 
install gtts it says "requirement already satisfied. So what should I do?

**Comment by darrelwright** [comment] 2022-02-24 22:01
If I enter "gtts-cli 'hello' --output hello.mp3 it works. So should the 
uba command be using gtts-cli rather than gtts?

**Comment by darrelwright** [comment] 2022-02-25 01:53
anything happening on this yet?

**Comment by eliranwong** [comment] 2022-03-02 22:34
Hi Darrel, I am sorry I cannot reproduce your issue on my side.  I think you might already install gTTS.

Please take this feature as bonus, not essential.

I develop this for webtop version, as I now use mainly webtop version.  As webtop version experience is consistent across different platforms, my priority is to make sure everything work in webtop version first.

I think it should work on non-web top version, but if not, I may simply disable this option in non-webtop version so this issue won't trouble you.

**Comment by darrelwright** [comment] 2022-03-02 22:51
Hey Eliran,

It is not a problem for me. I was just hoping the mp3 side might allow 
an easier playing scripture without verse numbers. I am still thoroughly 
enjoying uba and it is still my "go-to" bible app. I do still hope we do 
some more with LXX and morphology searching as we can do with MIB. It's 
good having you back working on stuff!

Darrel

**Comment by eliranwong** [comment] 2022-03-02 23:01
I think of a possible solution, try:

> cd UniqueBible

> source venv/bin/activate

> pip3 install gTTS

reason: One thing is different between webtop and non-webtop version.  UBA webtop version uses globally installed package as well as those locally installed in virtual environment.  Non-webtop version uses python packages locally installed in virtual environment ONLY.  If users install gTTS globally, it may not work when they run UBA with virtual environment.

give it a try and let me know.  thanks.

**Comment by eliranwong** [comment] 2022-03-02 23:03
bty, you mentioned verse number.  I will integrate toggle verse reference into menu layout.  I know there is a plugin already, but it may be easier to make it available by default.

**Comment by darrelwright** [comment] 2022-03-02 23:05
Wow! that worked! I can save text as mp3!

**Comment by darrelwright** [comment] 2022-03-02 23:06
Cool!

**Comment by eliranwong** [comment] 2022-03-02 23:28
closing this issue now.

bty, I may add speaker button next to verse number, so users can listen each verse easily.

**Closed by eliranwong** 2022-03-02 23:28 UTC

**Comment by darrelwright** [comment] 2022-03-02 23:29
I like that idea. Thanks for helping me!

**Comment by darrelwright** [comment] 2022-03-11 04:25
Well, upgraded to 28.32, downloaded a fresh NET bible, but I cannot get 
musical symbols to show either on chapter or verse. I submitted a 
response on github. Am I missing something?
