### ISSUE TITLE
Can't open a Bible in Bible window

### ISSUE THREAD

**Issue by frank4532** [eliranwong/UniqueBible#1052] opened 2022-06-01 16:00 UTC
Hi,
after last update, 30.19, it's impossible to open a Bible in Bible window both in desktop and webtop version. I tried several times with different Bibles.

**Comment by frank4532** [comment] 2022-06-01 17:00
Windows 10

**Comment by eliranwong** [comment] 2022-06-01 22:56
please try to enable fixLoadingContent and see if it works and let me know.  thanks.

<img width="835" alt="Screenshot 2022-06-01 at 23 55 32" src="https://user-images.githubusercontent.com/25262722/171514949-0591aae6-aa8e-4844-bb81-5eca78bc5c31.png">

**Comment by otseng** [comment] 2022-06-02 00:30
I think it's because self.bibleSelection is only defined in MaterialMainWindow.py, so other layouts are having problems.

**Comment by frank4532** [comment] 2022-06-02 06:20
I tried. I enabled fixLoadingContent but it doesn't work. Thanks

**Comment by eliranwong** [comment] 2022-06-02 08:20
> self.bibleSelection

@otseng You are right.  that's the issue.  @frank4532 I can now see it when I switch to the old Focus menu layout.  I will upload the fix soon.

**Comment by eliranwong** [comment] 2022-06-02 23:12
Great.  closing now as the issue is solved.

**Closed by eliranwong** 2022-06-02 23:12 UTC
Labels: bug
