### ISSUE TITLE
UniqueBible fail to start

### ISSUE THREAD

**Issue by AlainWill** [eliranwong/UniqueBible#1341] opened 2023-03-09 21:45 UTC
hi everyone need some help please!
i am using windows 11 on pc and it (up to date)...I install chocolate then python as shown in the link: https://github.com/eliranwong/UniqueBible/wiki/Install-on-Windows
same as UniqueBible everything install fine...but when i start (python .\UniqueBible\uba.py) with (Powershell)..It start ok...but it cant finish install missing module it says: "Required feature 'Qt Graphical Interface Layer' is not enabled.
Run 'pip3 install qtpy' to install it first!"
 
Thank in advance the help!

**Comment by eliranwong** [comment] 2023-03-09 21:50
are you sure you have the latest codes to install.  I found the same issue yesterday, but I fixed it.  The latest code should work.  Please kindly let me know.

**Comment by AlainWill** [comment] 2023-03-10 20:03
i install python 3.11.2
but i get this :
> python D:\Users\UniqueBible\uba.py
Setting up environment ...
> pip tool failed to be updated!
Installing 'gdown' ...
b'\r\n[notice] A new release of pip available: 22.3.1 -> 23.0.1\r\n[notice] To update, run: python.exe -m pip install --upgrade pip\r\n'
Installed!
Installing 'babel' ...
b'\r\n[notice] A new release of pip available: 22.3.1 -> 23.0.1\r\n[notice] To update, run: python.exe -m pip install --upgrade pip\r\n'
Installed!
Installing 'apsw' ...
b'\r\n[notice] A new release of pip available: 22.3.1 -> 23.0.1\r\n[notice] To update, run: python.exe -m pip install --upgrade pip\r\n'
Installed!
Installing 'prompt_toolkit' ...
b'\r\n[notice] A new release of pip available: 22.3.1 -> 23.0.1\r\n[notice] To update, run: python.exe -m pip install --upgrade pip\r\n'
Installed!
Installing 'qtpy' ...
b'\r\n[notice] A new release of pip available: 22.3.1 -> 23.0.1\r\n[notice] To update, run: python.exe -m pip install --upgrade pip\r\n'
Required feature 'Qt Graphical Interface Layer' is not enabled.
Run 'pip3 install qtpy' to install it first!

**Comment by eliranwong** [comment] 2023-03-10 21:28
I think there was a bug when you download the application.

I just tried to do a fresh installation.  Everything looks fine.

If you don't mind, you may delete the current one and re-download again:

starting from "git clone https://github.com/eliranwong/UniqueBible" as described in https://github.com/eliranwong/UniqueBible/wiki/Install-on-Windows#download-uba--run

I am sorry for the trouble.  I am sure the issue was fixed with the latest update.  So re-downloading should work.

**Comment by AlainWill** [comment] 2023-03-10 22:49
Yesssss it working now i did as you said and now everything work fine...thanks very much may God bless ..and again thanks

**Comment by eliranwong** [comment] 2023-03-11 13:28
I am glad that the issue is now solved.  I am closing this post now.

**Closed by eliranwong** 2023-03-11 13:28 UTC
